# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'SnapLayout' do
pod 'SnapKit', '~> 0.12.0'
end

target 'SnapLayoutTests' do

end

